# fly.toml app configuration file generated for omni-parser-app-dry-dust-2399 on 2024-12-27T15:11:07+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'omni-parser-app-dry-dust-2399'
primary_region = 'fra'
swap_size_mb = 32768

[build]

[http_service]
  internal_port = 7860
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '16gb'
  cpu_kind = 'performance'
  cpus = 4
